### PR TITLE
hb-feature/GREY-251 Subjects page: autoupdating dictionary lists

### PR DESCRIPTION
**Pull request by alexcoach**

### CODE REVIEW

**Comment by seanbolak** [comment]
@alexcoach , in the future when we have a branch that is applicable to both hb-develop and regular develop lets just use feature/{name} and create a PR from that feature branch into both develop branches.

**Comment by seanbolak** [comment]
@alexcoach I can't find this ticket number in our sprint. I'm validated that they're complete before I merge them. I've reviewed this and it looks good, but It's not in our Sprint 1 v 1.4

**Comment by alexcoach** [comment]
it was created by our QA and I decided to fix it without any sprint. What to do with it now?

**Comment by seanbolak** [comment]
Holding for now

**Pull request merged**
