### PR TITLE
GREY-618 Fix Tagged In User

### PR DESCRIPTION
**Pull request by HarryQuid**
#### Related JIRA tickets:
https://jira.amida-tech.com/browse/GREY-618
#### How should this be manually tested?
http://localhost:8081/#/policy/edit/1
#### Screenshots (if appropriate):

screen shot 2016-12-09 at 8 57 14 am

### CODE REVIEW

**Comment by hrickards** [comment]
@HarryQuid waiting for screenshot for Ekavali

**Comment by HarryQuid** [comment]
@hrickards , screenshot added,

**Comment by HarryQuid** [comment]
@ekavaliM , @hrickards 

Could you review this?

**Comment by hrickards** [comment]
Looks good from a cursory glance, merging for further QA 🏳️‍🌈

**Pull request merged**
