### PR TITLE
Feature/grey 633

### PR DESCRIPTION
**Pull request by HarryQuid**
#### What's this PR do?
Fix Counts on Project Page
#### Related JIRA tickets:
https://jira.amida-tech.com/browse/GREY-633
#### How should this be manually tested?
http://localhost:8081/#/pm/9

### CODE REVIEW

**Comment by hrickards** [comment]
@HarryQuid on some projects I'm getting the following screenshot and corresponding error:

image
image

**Comment by HarryQuid** [comment]
@hrickards , could you give me link to erroneous page?

**Comment by hrickards** [comment]
@HarryQuid it looks as though they're the projects without any tasks. Examples (using the indaba-dev.amida-demo / hcsc.amida-demo backend) are:
* http://localhost:8081/#/pm/3
* http://localhost:8081/#/pm/7

**Comment by HarryQuid** [comment]
@hrickards ,it's fixed

**Comment by hrickards** [comment]
@HarryQuid perfect

**Pull request merged**
