### PR TITLE
Bug/inba 440 resolve constraint on users

### PR DESCRIPTION
**Pull request by Perry5**
#### What's this PR do?
- Adds soft delete for users and checks everywhere to make sure deleted users are not added to projects and don't show up. Also adds ability to re-invite a deleted user

#### Related JIRA tickets:
[440](https://jira.amida-tech.com/browse/INBA-440)
[378](https://jira.amida-tech.com/browse/INBA-378)

#### How should this be manually tested?
- Create a project, add users
- Delete a user. Look in the DB and make sure that user was marked as deleted with a time stamp
- Try some other stuff to retrieve the deleted user- they shouldn't show up. You can use postman for this
- Re-invite that user. They should be un-marked as deleted
- Try adding a deleted user to a project- They shouldn't be "found"

#### Any background context you want to provide?
You might need to re-seed your DB by running one of the integration tests:
`node_modules/.bin/mocha test/user.integration.js --bail -t 10000`

### CODE REVIEW

**Comment by jmfadeley** [comment]
From the `user.integration.js`:

image

**Comment by Perry5** [comment]
@jmfadeley @sirctseb Fixed! Tests should pass now.

**Comment by jmfadeley** [comment]
@Perry5 So a different test is failing. However, it's also failing on the `develop` branch.

**Comment by jmfadeley** [comment]
image

**Comment by jmfadeley** [comment]
Something is up.... it doesn't look like the seed scripts are putting `isDeleted` into the user table.

**Comment by jmfadeley** [comment]
So the current code in the userReducer calls $unset for a deletion:
    case type.DELETE_USER_SUCCESS:
        return update(state, {
            users: { $unset: [userIndex] },
        });

Unset is an odd one... it's like it removes an index from an array but leaves something undefined there. I think it's intended more for objects. I'll push a PR to go with this that uses $splice instead. 

image

**Pull request merged**
