### PR TITLE
Task/inba 379 stages soft delete

### PR DESCRIPTION
**Pull request by Perry5**
#### What's this PR do?
Add soft delete for stages

#### Related JIRA tickets:
https://jira.amida-tech.com/browse/INBA-379

#### How should this be manually tested?
- Create a project
- go through the flow of adding tasks, users etc
- Use a REST client to delete a stage: `http://localhost:3005/testorg/v0.2/workflows/:id/steps`
- Check to make sure the stages / workflowSteps associated with that workflow is marked as deleted- you can look in the DB and also on the front end.
- Delete a workflow and make sure that the steps within that workflow are deleted

#### Any background context you want to provide?
Schema changed so you will need to re-run an integration test or something. 
`node_modules/.bin/mocha test/user.integration.js --bail -t 10000`

### CODE REVIEW

**Comment by Perry5** [comment]
This was this currently works is that you pass in a workflow ID and all stages under that workflow ID get deleted. Is that how we want this to work? or do we want to be able to delete a single stage by itself?

**Comment by jmfadeley** [comment]
I think we want to be able to delete a single stage.

**Comment by sirctseb** [comment]
@Perry5 I'm still checking if this works and I can integrate it with the client, but I'm not sure if using the existing workflow endpoint is a good idea. The `stepId` in the url now means different things to different HTTP methods. For GET it is actually the workflow id an for DELETE it is the step id, and for PUT it's the workflow id again and there are step ids in the body. Is there a way we can put the individual step DELETE at `DELETE /workflows/{workflowId}/steps/{stepId}` or just `DELETE /steps/stepID`?

**Comment by sirctseb** [comment]
@Perry5 It works. I integrated it into my frontend branch for deleting stages 👍. I can approve if we're ok with the endpoints as they are or we want to fix them in a later ticket.
CC @jmfadeley

**Comment by jmfadeley** [comment]
Taking a quick look now.

**Comment by jmfadeley** [comment]
Almost gave me a heart attack about the workflows over workflow steps. Looks good.

**Pull request merged**
