### PR TITLE
Js beautify

### PR DESCRIPTION
**Pull request by jsachs**

### CODE REVIEW

**Comment by jsachs** [comment]
GREY-17 finish beautification

**Comment by igiware** [comment]
hi,
are you planning to merge beautification changes into master in the near future? or better to cherry-pick your changes into ntrlab branch directly? It's need to sync code formatting

**Comment by jsachs** [comment]
Are you guys going to continue to use `master`? Our plan is to have `production` become the default branch.

I can merge my changes into master, but if we need to wait before merging, you can just install `grunt-jsbeautifier` to make it easier when we do merge.

**Comment by UglyEugen** [comment]
Jacob, we already switched to `ntrlab` branch as agreed with @kachok. He said also that you (amida) will be responsible for merging code to `master` from now on and it would be reasonable if we'll use `jsbeautifier` in our branch too to minimize the number of conflicts in future.
But I think it wouldn't be enough just to install `jsbeautifier` - some build task need to be configured aslo, right?

**Comment by jsachs** [comment]
Correct, you'll need to run it with a grunt task. You can look at how I set it up in the backend and client code on the `develop` branch.

Am I correct that you are no longer using `master` at all?

**Comment by UglyEugen** [comment]
yes, we're not using `master` anymore

**Pull request merged**
