### PR TITLE
Bug/inba 752 po notify users new task project

### PR DESCRIPTION
**Pull request by Perry5**
Sends out email / internal notification when a user is assigned a new task and when a users task is now active.

Ticket: https://jira.amida-tech.com/browse/INBA-752

To Test:
1.
- Create a project (or use an existing project)
- Assign a new task to a user with a legit email that you can check
- Check to make sure that user got an email and also an internal notification.

2.
- Assign a task to user A in stage 1
- Assign a task to user B in stage 2
- Complete the task for user A in stage 1
- Ensure that user B gets an email and internal notification saying their task is now active

The email being sent out for task activation could probably contain some more information- but this took unnecessarily long to get done and it seems like to do that will require some pretty serious modifications- so I would rather separate that into a different ticket:
https://jira.amida-tech.com/browse/INBA-757

### CODE REVIEW

**Comment by sirctseb** [comment]
Can we do a quick sweep of commented code, empty lines, and console logs?

**Comment by Perry5** [comment]
Done!

**Comment by jmfadeley** [comment]
@Perry5 I noticed interesting behavior. If User A and B are the same, the user does not get the "Task Activated" email upon stage 1's completion. But B will receive it if he/she is not A. I don't have a problem with this though.

**Comment by Perry5** [comment]
@jmfadeley Yes, this is intentional. I believe the idea is that if you are User A and you Complete a task in Stage 1, you shouldn't have to be notified that you have completed your task since you completed it yourself :-)

` if (req.user.id !== task.userIds[i]) { // don't send self notification`

**Pull request merged**
