### PR TITLE
Feature/grey 607

### PR DESCRIPTION
**Pull request by HarryQuid**
#### What's this PR do?
Change ext Editor
#### Related JIRA tickets:
https://jira.amida-tech.com/browse/GREY-607
#### How should this be manually tested?
http://localhost:8081/#/policy/edit/7

### CODE REVIEW

**Comment by hrickards** [comment]
@HarryQuid great! Only issue I can see is this breaks the PDF printing, giving the following console error:

image

**Comment by HarryQuid** [comment]
@hrickards , could you check it again?

It works on my computer

**Comment by hrickards** [comment]
@HarryQuid I'm still seeing the issue: if I insert a table anywhere then clicking "Print PDF" yields the above error. I'll merge and we'll see if it's a problem on staging.

**Comment by hrickards** [comment]
@HarryQuid you're right, I don't see the issue on staging. Moving the tickets to QA. Thanks Harry!

**Pull request merged**
