### PR TITLE
GREY-608 Add Line Number

### PR DESCRIPTION
**Pull request by HarryQuid**
#### What's this PR do?
Add Line Number
#### Related JIRA tickets:
https://jira.amida-tech.com/browse/GREY-608
#### How should this be manually tested?
http://localhost:8081/#/policy/edit/1
#### Screenshots (if appropriate):
[policy (15).pdf](https://github.com/amida-tech/greyscale/files/642626/policy.15.pdf)

### CODE REVIEW

**Comment by hrickards** [comment]
@HarryQuid couple of things:
* let's 1-index line numbers for consistency with the UI
* I don't see line numbers in the Description, Rationale, Contract, Pricing or Coding sections (on the Lumbar Spinal Fusion 2016 policy)
* I don't see a section header for Rationale, just the content right below the Medicare content
* Non-ASCII chars pop up occasionally -- on the Lumbar Spinal Fusion 2016 policy, I see the two screenshots below in the draft, but not in the UI

image
image
 
* When there are numbered bullets, the line numbers should go before the numbered bullet, not after. For example, in the screenshot below the bullets should read "7. 1.", "8. 2." (and the 7 and 8 should be aligned with the other numbers if easy, but not a big deal if not).

image

**Comment by HarryQuid** [comment]
@hrickards , i have fixed the issues

**Comment by hrickards** [comment]
@HarryQuid almost there, a couple more little things:
* The line numbers don't match up exactly what the web UI shows. Take a look at Line 3 of _Coverage_ of `Lumbar Spinal Fusion 2016`. It's not marked as a line in the web UI, so line 2 matches up but line 4 doesn't.
* Still not seeing a header for the _Rationale_ section?
* Can we keep line numbers on the same line as the line text and drop the preceding `Line` text?

Thanks Harry! :)

**Comment by HarryQuid** [comment]
@hrickards , it is fixed,

**Comment by hrickards** [comment]
@HarryQuid I'm seeing issues with the order of numbers in numbered lists. Take the list from lines 12 through 34 of `Lumbar Spinal Fusion 2016`. The numbers increase as normal in the web UI, but in the PDF go `1, 2, 4, 3, 4, 4, 6, 7, 3, 4`. The texts are right though, just the numbers are wrong.

**Comment by HarryQuid** [comment]
I debug the issues, and it was actually jsPDF rendering issue, i am not quite sure how to fix this at the moment,

jsPDF renders pdf from html, and when it renders the html it makes that error. @hrickards

**Comment by hrickards** [comment]
@HarryQuid got it, thanks Harry. Merging this and ticketing the jsPDF bug.

**Pull request merged**
